apiVersion: apps/v1
kind: Deployment
metadata:
  name: cef-app-training-http
  namespace: cef
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cef-app-training-http
  template:
    metadata:
      labels:
        app: cef-app-training-http
    spec:
      containers:
      - name: cef-app-training-container-http
        image: cefcefcef/cef-app-training-httpv3:v3
        ports:
        - containerPort: 15601
