services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "15601:15601"
  web:
    build:
      context: ./static
      dockerfile: Dockerfile
    ports:
      - "5000:15601"
  redis:
    image: "redis:alpine"